controller_manager:
    ros__parameters:
        update_rate: 30
        use_sim_time: true

        # diff drive controller:
        diff_controller:
            type: diff_drive_controller/DiffDriveController
        
        # joint state controller:
        joint_broad:
            type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
    ros_parameters:

        publish_rate: 30.0

        base_frame_id: base_link
        left_wheel_names: ['RLM_RLW_joint', 'FLM_FLW_joint']
        right_wheel_names: ['RRM_RRW_joint', 'FRM_FRW_joint']

        wheel_separation: 0.288
        wheel_radius: 0.0925

        use_stamped_vel: false
        